[2023-12-26T08:35:42.996+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sensor_target_dag.waiting_end_parent_dag manual__2023-12-26T08:35:41.608520+00:00 [queued]>
[2023-12-26T08:35:43.004+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sensor_target_dag.waiting_end_parent_dag manual__2023-12-26T08:35:41.608520+00:00 [queued]>
[2023-12-26T08:35:43.004+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T08:35:43.004+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-26T08:35:43.005+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T08:35:43.023+0000] {taskinstance.py:1383} INFO - Executing <Task(ExternalTaskSensor): waiting_end_parent_dag> on 2023-12-26 08:35:41.608520+00:00
[2023-12-26T08:35:43.029+0000] {standard_task_runner.py:55} INFO - Started process 1546 to run task
[2023-12-26T08:35:43.032+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sensor_target_dag', 'waiting_end_parent_dag', 'manual__2023-12-26T08:35:41.608520+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/sensor_target_dag.py', '--cfg-path', '/tmp/tmpbeup_fq5']
[2023-12-26T08:35:43.032+0000] {standard_task_runner.py:83} INFO - Job 163: Subtask waiting_end_parent_dag
[2023-12-26T08:35:43.088+0000] {task_command.py:376} INFO - Running <TaskInstance: sensor_target_dag.waiting_end_parent_dag manual__2023-12-26T08:35:41.608520+00:00 [running]> on host d2fc15a9183d
[2023-12-26T08:35:43.129+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:549: DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
  option = self._get_option_from_config_file(deprecated_key, deprecated_section, key, kwargs, section)

[2023-12-26T08:35:43.175+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sensor_target_dag
AIRFLOW_CTX_TASK_ID=waiting_end_parent_dag
AIRFLOW_CTX_EXECUTION_DATE=2023-12-26T08:35:41.608520+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-26T08:35:41.608520+00:00
[2023-12-26T08:35:43.176+0000] {external_task.py:206} INFO - Poking for tasks ['end'] in dag sensor_parent_dag on 2023-12-26T08:35:41.608520+00:00 ... 
[2023-12-26T08:36:43.243+0000] {external_task.py:206} INFO - Poking for tasks ['end'] in dag sensor_parent_dag on 2023-12-26T08:35:41.608520+00:00 ... 
[2023-12-26T08:36:58.879+0000] {local_task_job.py:228} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-12-26T08:36:58.881+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1546. PIDs of all processes in the group: [1546]
[2023-12-26T08:36:58.881+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1546
[2023-12-26T08:36:58.881+0000] {taskinstance.py:1562} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-12-26T08:36:58.934+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1546, status='terminated', exitcode=0, started='08:35:42') (1546) terminated with exit code 0
[2023-12-26T08:40:19.212+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sensor_target_dag.waiting_end_parent_dag manual__2023-12-26T08:35:41.608520+00:00 [queued]>
[2023-12-26T08:40:19.220+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sensor_target_dag.waiting_end_parent_dag manual__2023-12-26T08:35:41.608520+00:00 [queued]>
[2023-12-26T08:40:19.220+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T08:40:19.220+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-26T08:40:19.220+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T08:40:19.242+0000] {taskinstance.py:1383} INFO - Executing <Task(ExternalTaskSensor): waiting_end_parent_dag> on 2023-12-26 08:35:41.608520+00:00
[2023-12-26T08:40:19.249+0000] {standard_task_runner.py:55} INFO - Started process 1768 to run task
[2023-12-26T08:40:19.252+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sensor_target_dag', 'waiting_end_parent_dag', 'manual__2023-12-26T08:35:41.608520+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/sensor_target_dag.py', '--cfg-path', '/tmp/tmps6ea3h4q']
[2023-12-26T08:40:19.252+0000] {standard_task_runner.py:83} INFO - Job 165: Subtask waiting_end_parent_dag
[2023-12-26T08:40:19.312+0000] {task_command.py:376} INFO - Running <TaskInstance: sensor_target_dag.waiting_end_parent_dag manual__2023-12-26T08:35:41.608520+00:00 [running]> on host d2fc15a9183d
[2023-12-26T08:40:19.347+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:549: DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
  option = self._get_option_from_config_file(deprecated_key, deprecated_section, key, kwargs, section)

[2023-12-26T08:40:19.393+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sensor_target_dag
AIRFLOW_CTX_TASK_ID=waiting_end_parent_dag
AIRFLOW_CTX_EXECUTION_DATE=2023-12-26T08:35:41.608520+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-26T08:35:41.608520+00:00
[2023-12-26T08:40:19.393+0000] {external_task.py:206} INFO - Poking for tasks ['end'] in dag sensor_parent_dag on 2023-12-26T08:35:41.608520+00:00 ... 
[2023-12-26T08:41:19.458+0000] {external_task.py:206} INFO - Poking for tasks ['end'] in dag sensor_parent_dag on 2023-12-26T08:35:41.608520+00:00 ... 
[2023-12-26T08:41:45.230+0000] {local_task_job.py:228} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-12-26T08:41:45.233+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1768. PIDs of all processes in the group: [1768]
[2023-12-26T08:41:45.233+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1768
[2023-12-26T08:41:45.233+0000] {taskinstance.py:1562} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-12-26T08:41:45.243+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 211, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1564, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-12-26T08:41:45.248+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=sensor_target_dag, task_id=waiting_end_parent_dag, execution_date=20231226T083541, start_date=20231226T084019, end_date=20231226T084145
[2023-12-26T08:41:45.266+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 165 for task waiting_end_parent_dag ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(sensor_target_dag, waiting_end_parent_dag, manual__2023-12-26T08:35:41.608520+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'waiting_end_parent_dag', 'dag_id': 'sensor_target_dag', 'run_id': 'manual__2023-12-26T08:35:41.608520+00:00', 'map_index': -1, 'start_date': datetime.datetime(2023, 12, 26, 8, 40, 19, 213395, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2023, 12, 26, 8, 41, 45, 247599, tzinfo=Timezone('UTC')), 'duration': 86}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 1768)
[2023-12-26T08:41:45.288+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1768, status='terminated', exitcode=1, started='08:40:18') (1768) terminated with exit code 1
