[2023-12-25T15:40:49.321+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_python_dag.task_a manual__2023-12-25T15:40:48.435352+00:00 [queued]>
[2023-12-25T15:40:49.329+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_python_dag.task_a manual__2023-12-25T15:40:48.435352+00:00 [queued]>
[2023-12-25T15:40:49.329+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-25T15:40:49.329+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-25T15:40:49.329+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-25T15:40:49.348+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): task_a> on 2023-12-25 15:40:48.435352+00:00
[2023-12-25T15:40:49.355+0000] {standard_task_runner.py:55} INFO - Started process 735 to run task
[2023-12-25T15:40:49.358+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_python_dag', 'task_a', 'manual__2023-12-25T15:40:48.435352+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/my_python_dag.py', '--cfg-path', '/tmp/tmp4utke8yq']
[2023-12-25T15:40:49.358+0000] {standard_task_runner.py:83} INFO - Job 72: Subtask task_a
[2023-12-25T15:40:49.411+0000] {task_command.py:376} INFO - Running <TaskInstance: my_python_dag.task_a manual__2023-12-25T15:40:48.435352+00:00 [running]> on host 4d1993f85b22
[2023-12-25T15:40:49.454+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:549: DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
  option = self._get_option_from_config_file(deprecated_key, deprecated_section, key, kwargs, section)

[2023-12-25T15:40:49.529+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_python_dag
AIRFLOW_CTX_TASK_ID=task_a
AIRFLOW_CTX_EXECUTION_DATE=2023-12-25T15:40:48.435352+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-25T15:40:48.435352+00:00
[2023-12-25T15:40:49.531+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 173, in execute
    self.op_kwargs = self.determine_kwargs(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 184, in determine_kwargs
    return KeywordParameters.determine(self.python_callable, self.op_args, context).unpacking()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/operator_helpers.py", line 161, in determine
    raise ValueError(f"The key {name!r} in args is a part of kwargs and therefore reserved.")
ValueError: The key 'fname' in args is a part of kwargs and therefore reserved.
[2023-12-25T15:40:49.542+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=my_python_dag, task_id=task_a, execution_date=20231225T154048, start_date=20231225T154049, end_date=20231225T154049
[2023-12-25T15:40:49.558+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 72 for task task_a (The key 'fname' in args is a part of kwargs and therefore reserved.; 735)
[2023-12-25T15:40:49.611+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-12-25T15:40:49.640+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
