[2023-12-25T15:38:28.762+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_python_dag.task_a scheduled__2023-12-24T00:00:00+00:00 [queued]>
[2023-12-25T15:38:28.769+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_python_dag.task_a scheduled__2023-12-24T00:00:00+00:00 [queued]>
[2023-12-25T15:38:28.770+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-25T15:38:28.770+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-25T15:38:28.770+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-25T15:38:28.787+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): task_a> on 2023-12-24 00:00:00+00:00
[2023-12-25T15:38:28.794+0000] {standard_task_runner.py:55} INFO - Started process 622 to run task
[2023-12-25T15:38:28.796+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_python_dag', 'task_a', 'scheduled__2023-12-24T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/my_python_dag.py', '--cfg-path', '/tmp/tmpprllcy3w']
[2023-12-25T15:38:28.797+0000] {standard_task_runner.py:83} INFO - Job 70: Subtask task_a
[2023-12-25T15:38:28.813+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:549: DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
  option = self._get_option_from_config_file(deprecated_key, deprecated_section, key, kwargs, section)

[2023-12-25T15:38:28.852+0000] {task_command.py:376} INFO - Running <TaskInstance: my_python_dag.task_a scheduled__2023-12-24T00:00:00+00:00 [running]> on host 4d1993f85b22
[2023-12-25T15:38:28.894+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:549: DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
  option = self._get_option_from_config_file(deprecated_key, deprecated_section, key, kwargs, section)

[2023-12-25T15:38:28.935+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_python_dag
AIRFLOW_CTX_TASK_ID=task_a
AIRFLOW_CTX_EXECUTION_DATE=2023-12-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-24T00:00:00+00:00
[2023-12-25T15:38:28.936+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 173, in execute
    self.op_kwargs = self.determine_kwargs(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 184, in determine_kwargs
    return KeywordParameters.determine(self.python_callable, self.op_args, context).unpacking()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/operator_helpers.py", line 161, in determine
    raise ValueError(f"The key {name!r} in args is a part of kwargs and therefore reserved.")
ValueError: The key 'filename' in args is a part of kwargs and therefore reserved.
[2023-12-25T15:38:28.944+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=my_python_dag, task_id=task_a, execution_date=20231224T000000, start_date=20231225T153828, end_date=20231225T153828
[2023-12-25T15:38:28.969+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 70 for task task_a (The key 'filename' in args is a part of kwargs and therefore reserved.; 622)
[2023-12-25T15:38:29.008+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-12-25T15:38:29.033+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
